version: "2"
services:
  postgres:
    image: postgres:alpine
  proxy:
    image: shipyard/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  umiushi:
    env_file: .environment
    build:
      context: .
      dockerfile: Dockerfile-quick
    entrypoint: /src/bin/umiushi
    working_dir: /src
    ports:
      - "8080:8080"
    links:
      - postgres
      - proxy
    logging:
      driver: "json-file"
    environment:
      DOCKER_PORT:        "tcp://proxy:2375"
      POSTGRES_PORT:      "tcp://postgres:5432"
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  ""
      POSTGRES_DATABASE:  postgres
