FROM swift

ADD . /src/webui

RUN apt-get update  --yes \
 && apt-get install --yes \
            autoconf \
            automake \
            bash \
            cmake \
            curl \
            git \
            inotify-tools \
            python-pip \
            unzip \
            libc6-dev \
            libmagic-dev \
            libssl-dev \
            libtool \
 && pip install --upgrade pip \
 && pip install --upgrade virtualenv \
 && pip install hererocks \
 && hererocks --luajit=2.1 --luarocks=^ /usr \
 && luarocks install luasec \
 && apt-get clean \
 && useradd --home=/data --shell=/bin/bash user \
 && cd /src/webui/ \
 && luarocks make rockspec/webui-worker-master-1.rockspec \
             INOTIFY_INCDIR="/usr/include/x86_64-linux-gnu" \
 && rm -rf        /src/webui \
 && apt-get remove --yes \
            autoconf \
            automake \
            cmake \
            python-pip \
            libtool \
 && apt-get autoremove --yes \
 && apt-get clean

# VOLUME      ["/data"]
# EXPOSE      8080
# USER        user
# WORKDIR     /data
# ENTRYPOINT  ["webui-worker"]
