FROM webui-swift-dev

ADD . /src/webui

RUN cd /src/webui/ \
 && luarocks make rockspec/webui-worker-master-1.rockspec \
             INOTIFY_INCDIR="/usr/include/x86_64-linux-gnu" \
 && rm -rf /src/webui

VOLUME      ["/data"]
EXPOSE      8080
USER        user
WORKDIR     /data
ENTRYPOINT  ["webui-worker"]
