version: "2"
services:
  postgres:
    image: postgres
  redis:
    image: redis:3.0.7 # because of bug in qless
  webui:
    env_file: .environment
    build:
      context: .
      dockerfile: Dockerfile-quick
    entrypoint: webui
    ports:
      - "8080:8080"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
    environment:
      REDIS_PORT:         "tcp://redis:6379"
      POSTGRES_PORT:      "tcp://postgres:5432"
      POSTGRES_USER:      postgres
      POSTGRES_PASSWORD:  ""
      POSTGRES_DATABASE:  postgres
