export const ADD_GROWL = 'ADD_GROWL'
export const DISMISS_GROWL = 'DISMISS_GROWL'

export const EDITOR_CHANGE_ACTIVE_FILE = 'EDITOR_CHANGE_ACTIVE_FILE'
export const EDITOR_CLOSE_FILE = 'EDITOR_CLOSE_FILE'
export const EDITOR_TOGGLE_DIRECTORY = 'EDITOR_TOGGLE_DIRECTORY'
export const EDITOR_UPDATE_FILE_CONTENT = 'EDITOR_UPDATE_FILE_CONTENT'

export const LIST_REPOSITORIES = 'LIST_REPOSITORIES'

export const LIST_FILES = 'LIST_FILES'
export const GET_FILE = 'GET_FILE'
export const PATCH_FILE = 'PATCH_FILE'

export const BASH_EXECUTE = 'BASH_EXECUTE'
